### ISSUE TITLE
Upgrade to ZIO 2.0

### ISSUE THREAD

**Issue by swoogles** [softwaremill/sttp#1161]
ZIO is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

To assist with the migration, follow this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

# Tasks

- [x] copy all `zio` backend implementations and integrations to `zio1`; remember to add the new modules to `build.sbt` aggregates
- [ ] change the dependencies in `zio` modules to use 2.x. The `zio1` modules keep the 1.x dependencies
- [ ] update documentation to cover 2.x only, with a pointer to `zio1` modules

**Comment by adamw** [comment]
Downstream dependencies:
https://github.com/zio/zio-nio/issues/422
https://github.com/zio/interop-reactive-streams/issues/296

Optional: 
https://github.com/zio/zio-json/issues/463
https://github.com/zio/zio-telemetry/issues/449
